services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:centos7
    restart: on-failure
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./jenkins-volume:/var/jenkins_home"
